/*
Deployment script for Jordflytning

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Jordflytning"
:setvar DefaultFilePrefix "Jordflytning"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "F:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\LOG\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

PRINT N'Altering [dbo].[Anmeldelse]...';


GO
ALTER TABLE [dbo].[Anmeldelse]
    ADD [TotalMaengdeJordIkkeFJ] INT NULL;


GO
PRINT N'Altering [dbo].[ModtagerAnlaeg]...';


GO
ALTER TABLE [dbo].[ModtagerAnlaeg]
    ADD [KommuneKode] INT NULL;


GO
PRINT N'Altering [dbo].[Person]...';


GO
ALTER TABLE [dbo].[Person]
    ADD [JordmodtagerAdvis] BIT DEFAULT ((0)) NOT NULL;


GO
PRINT N'Refreshing [dbo].[Anmeldelser godkendte]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Anmeldelser godkendte]';


GO
PRINT N'Refreshing [dbo].[MapModtagerAnlaeg]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[MapModtagerAnlaeg]';


GO
PRINT N'Update complete.';


GO
