//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyseDokument
    {
        public System.Guid Id { get; set; }
        public System.Guid StikproeveId { get; set; }
        public string Filnavn { get; set; }
        public System.DateTime Dato { get; set; }
    
        public virtual Stikproeve Stikproeve { get; set; }
    }
}
