//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyseForureningskomponent
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ForureningskomponentId { get; set; }
        public Nullable<System.Guid> StikproeveId { get; set; }
        public Nullable<System.Guid> EnhedId { get; set; }
        public decimal Vaerdi { get; set; }
    
        public virtual Enhed Enhed { get; set; }
        public virtual Forureningskomponent Forureningskomponent { get; set; }
        public virtual Stikproeve Stikproeve { get; set; }
    }
}
