//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anmeldelse
    {
        public Anmeldelse()
        {
            this.Advis = new HashSet<Advis>();
            this.Alarm = new HashSet<Alarm>();
            this.Anmeldelse1 = new HashSet<Anmeldelse>();
            this.Betaleringsoplysning = new HashSet<Betaleringsoplysning>();
            this.Interesant = new HashSet<Interesant>();
            this.Kommunikation = new HashSet<Kommunikation>();
            this.Log = new HashSet<Log>();
            this.PlanlagteStikproever = new HashSet<PlanlagteStikproever>();
            this.StatusAnmeldelse = new HashSet<StatusAnmeldelse>();
            this.Vognlaes = new HashSet<Vognlaes>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> KommuneId { get; set; }
        public Nullable<System.Guid> TransportoerId { get; set; }
        public System.Guid AnmelderId { get; set; }
        public Nullable<System.Guid> ModtagerAnlaegId { get; set; }
        public Nullable<System.Guid> BetalerId { get; set; }
        public Nullable<System.Guid> SagsbehandlerId { get; set; }
        public Nullable<System.Guid> RevisionAfAnmeldelse { get; set; }
        public decimal Nummer { get; set; }
        public string BemaerkningTilAnmeldelse { get; set; }
        public string BemaerkningTilKommune { get; set; }
        public string BemaerkningTilJordmodtager { get; set; }
        public string AarsagAfvisning { get; set; }
        public string BemarkningInternKommune { get; set; }
        public Nullable<int> KoertJordAlarm { get; set; }
        public string AnmelderSagsnummer { get; set; }
        public Nullable<System.DateTime> FlagSagsbehandler { get; set; }
        public Nullable<int> TotalMaengdeJordIkkeFJ { get; set; }
        public Nullable<System.Guid> FlagJordForurening { get; set; }
    
        public virtual ICollection<Advis> Advis { get; set; }
        public virtual ICollection<Alarm> Alarm { get; set; }
        public virtual ICollection<Anmeldelse> Anmeldelse1 { get; set; }
        public virtual Anmeldelse Anmeldelse2 { get; set; }
        public virtual ICollection<Betaleringsoplysning> Betaleringsoplysning { get; set; }
        public virtual ICollection<Interesant> Interesant { get; set; }
        public virtual Jordforureningsopslag Jordforureningsopslag { get; set; }
        public virtual ICollection<Kommunikation> Kommunikation { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<PlanlagteStikproever> PlanlagteStikproever { get; set; }
        public virtual ICollection<StatusAnmeldelse> StatusAnmeldelse { get; set; }
        public virtual ICollection<Vognlaes> Vognlaes { get; set; }
        public virtual Betaler Betaler { get; set; }
        public virtual Anmelder Anmelder { get; set; }
        public virtual Transportoer Transportoer { get; set; }
        public virtual ModtagerAnlaeg ModtagerAnlaeg { get; set; }
        public virtual Kommune Kommune { get; set; }
        public virtual Sagsbehandler Sagsbehandler { get; set; }
        public virtual Jord Jord { get; set; }
        public virtual Oprindelsessted Oprindelsessted { get; set; }
        public virtual AnmeldelseEffektivStatus AnmeldelseEffektivStatus { get; set; }
        public virtual Gebyr Gebyr { get; set; }
    }
}
