//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnmeldelseEffektivStatus
    {
        public System.Guid AnmeldelseId { get; set; }
        public Nullable<System.DateTime> Afsendt { get; set; }
        public Nullable<System.DateTime> BetalingAccepteret { get; set; }
        public Nullable<System.DateTime> BetalingAfvist { get; set; }
        public Nullable<System.DateTime> UnderBehandling { get; set; }
        public Nullable<System.DateTime> Godkendt { get; set; }
        public Nullable<System.DateTime> Afvist { get; set; }
        public Nullable<System.DateTime> JordAccepteret { get; set; }
        public Nullable<System.DateTime> JordAfvist { get; set; }
        public Nullable<System.DateTime> Afsluttet { get; set; }
        public Nullable<System.DateTime> Revideret { get; set; }
        public Nullable<System.DateTime> Aktiv { get; set; }
        public Nullable<System.DateTime> Oprettet { get; set; }
        public Nullable<System.DateTime> Gemt { get; set; }
        public Nullable<System.DateTime> ForureningsstatusAendret { get; set; }
    
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
