//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BemyndigedeAnmeldere
    {
        public System.Guid Id { get; set; }
        public System.Guid BetalerId { get; set; }
        public System.Guid AnmelderId { get; set; }
        public System.DateTime Oprettet { get; set; }
    
        public virtual Anmelder Anmelder { get; set; }
        public virtual Betaler Betaler { get; set; }
    }
}
