//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Besked
    {
        public Besked()
        {
            this.Advis = new HashSet<Advis>();
            this.Kommunikation = new HashSet<Kommunikation>();
            this.Alarm = new HashSet<Alarm>();
        }
    
        public System.Guid Id { get; set; }
        public string Tekst { get; set; }
        public System.DateTime Tid { get; set; }
    
        public virtual ICollection<Advis> Advis { get; set; }
        public virtual ICollection<Kommunikation> Kommunikation { get; set; }
        public virtual ICollection<Alarm> Alarm { get; set; }
    }
}
