//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Betaler
    {
        public Betaler()
        {
            this.StatusBetaler = new HashSet<StatusBetaler>();
            this.BogholderOpslagstavle = new HashSet<BogholderOpslagstavle>();
            this.BemyndigedeAnmeldere = new HashSet<BemyndigedeAnmeldere>();
            this.Anmeldelse = new HashSet<Anmeldelse>();
        }
    
        public System.Guid Id { get; set; }
    
        public virtual ICollection<StatusBetaler> StatusBetaler { get; set; }
        public virtual ICollection<BogholderOpslagstavle> BogholderOpslagstavle { get; set; }
        public virtual ICollection<BemyndigedeAnmeldere> BemyndigedeAnmeldere { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Anmeldelse> Anmeldelse { get; set; }
    }
}
