//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Betaleringsoplysning
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AnmeldelseId { get; set; }
        public string EAN { get; set; }
        public string SendesTilEmail { get; set; }
    
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
