//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartographer_Layers
    {
        public string TableOwner { get; set; }
        public string TableName { get; set; }
        public string KeyColumn { get; set; }
        public string GeometryColumn { get; set; }
        public string GeometryIndex { get; set; }
        public string StyleType { get; set; }
        public string StyleValue { get; set; }
        public int Epsg { get; set; }
        public double MinX { get; set; }
        public double MinY { get; set; }
        public double MaxX { get; set; }
        public double MaxY { get; set; }
    }
}
