//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delta
    {
        public System.Guid Id { get; set; }
        public System.Guid LogId { get; set; }
        public string Navn { get; set; }
        public string Foer { get; set; }
        public string Efter { get; set; }
    
        public virtual Log Log { get; set; }
    }
}
