//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentation
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DokumentationTypeId { get; set; }
        public string Filnavn { get; set; }
        public Nullable<System.Guid> JordId { get; set; }
        public System.DateTime OprindelsesDato { get; set; }
    
        public virtual DokumentationType DokumentationType { get; set; }
        public virtual Jord Jord { get; set; }
    }
}
