//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumenter
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ModtagerAnlaegId { get; set; }
        public string Filnavn { get; set; }
        public string Sti { get; set; }
    
        public virtual ModtagerAnlaeg ModtagerAnlaeg { get; set; }
    }
}
