//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaktureringUdtraek
    {
        public FaktureringUdtraek()
        {
            this.Gebyrer = new HashSet<Gebyr>();
        }
    
        public System.Guid Id { get; set; }
        public string Navn { get; set; }
        public System.DateTime OprettetDato { get; set; }
        public Nullable<System.DateTime> OverfoertDato { get; set; }
        public System.DateTime Skaeringsdato { get; set; }
    
        public virtual ICollection<Gebyr> Gebyrer { get; set; }
        public virtual Sagsbehandler OprettetAfSagsbehandler { get; set; }
        public virtual Sagsbehandler OverfoertAfSagsbehandler { get; set; }
    }
}
