//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmaoplysninger
    {
        public Firmaoplysninger()
        {
            this.Person = new HashSet<Person>();
        }
    
        public System.Guid Id { get; set; }
        public decimal CVR { get; set; }
        public string PNummer { get; set; }
        public string Firmanavn { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Postnummer { get; set; }
        public string Postdistikt { get; set; }
        public Nullable<decimal> Telefon { get; set; }
        public Nullable<decimal> EAN { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
