//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forureningskomponent
    {
        public Forureningskomponent()
        {
            this.Graensevaerdier = new HashSet<Graensevaerdier>();
            this.JordForureningskomponent = new HashSet<JordForureningskomponent>();
            this.AnalyseForureningskomponent = new HashSet<AnalyseForureningskomponent>();
        }
    
        public System.Guid Id { get; set; }
        public string Navn { get; set; }
        public Nullable<System.DateTime> Udloebsdato { get; set; }
        public Nullable<decimal> Sortering { get; set; }
        public string Kode { get; set; }
    
        public virtual ICollection<Graensevaerdier> Graensevaerdier { get; set; }
        public virtual ICollection<JordForureningskomponent> JordForureningskomponent { get; set; }
        public virtual ICollection<AnalyseForureningskomponent> AnalyseForureningskomponent { get; set; }
    }
}
