//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebyr
    {
        public Gebyr()
        {
            this.GebyrTidsregistrering = new HashSet<GebyrTidsregistrering>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<bool> Gebyrpligtig { get; set; }
        public Nullable<System.DateTime> BeslutningsDato { get; set; }
        public bool FrigivetTilFakturering { get; set; }
        public Nullable<System.DateTime> FrigivetTilFaktureringDato { get; set; }
        public string Bemaerkning { get; set; }
        public string FaktureringBemaerkning { get; set; }
    
        public virtual Anmeldelse Anmeldelse { get; set; }
        public virtual Sagsbehandler FrigivetAfSagsbehandler { get; set; }
        public virtual Sagsbehandler Sagsbehandler { get; set; }
        public virtual ICollection<GebyrTidsregistrering> GebyrTidsregistrering { get; set; }
        public virtual FaktureringUdtraek FaktureringUdtraek { get; set; }
    }
}
