//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GebyrTidsregistrering
    {
        public System.Guid Id { get; set; }
        public System.DateTime Dato { get; set; }
        public int Minutter { get; set; }
        public string Beskrivelse { get; set; }
    
        public virtual Opgavetype Opgavetype { get; set; }
        public virtual Gebyr Gebyr { get; set; }
        public virtual Sagsbehandler Sagsbehandler { get; set; }
    }
}
