//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Niras.Jordflytning.Core.Models;
    
    public partial class JordflytningEntities : DbContext
    {
        public JordflytningEntities()
            : base("name=JordflytningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdvisType> AdvisType { get; set; }
        public DbSet<AffaldType> AffaldType { get; set; }
        public DbSet<AndenOprindJordType> AndenOprindJordType { get; set; }
        public DbSet<Anmelder> Anmelder { get; set; }
        public DbSet<Betaler> Betaler { get; set; }
        public DbSet<Betaleringsoplysning> Betaleringsoplysning { get; set; }
        public DbSet<BetingelserJordtip> BetingelserJordtip { get; set; }
        public DbSet<BrugerProfil> BrugerProfil { get; set; }
        public DbSet<Cartographer_Layers> Cartographer_Layers { get; set; }
        public DbSet<Dokumentation> Dokumentation { get; set; }
        public DbSet<DokumentationType> DokumentationType { get; set; }
        public DbSet<Dokumenter> Dokumenter { get; set; }
        public DbSet<Enhed> Enhed { get; set; }
        public DbSet<Firmaoplysninger> Firmaoplysninger { get; set; }
        public DbSet<Forureningskomponent> Forureningskomponent { get; set; }
        public DbSet<Graensevaerdier> Graensevaerdier { get; set; }
        public DbSet<Interesant> Interesant { get; set; }
        public DbSet<JordanlaegType> JordanlaegType { get; set; }
        public DbSet<JordflytningType> JordflytningType { get; set; }
        public DbSet<JordForureningskomponent> JordForureningskomponent { get; set; }
        public DbSet<Jordmodtager> Jordmodtager { get; set; }
        public DbSet<Kommune> Kommune { get; set; }
        public DbSet<Konfig> Konfig { get; set; }
        public DbSet<Lastbil> Lastbil { get; set; }
        public DbSet<Matrikel> Matrikel { get; set; }
        public DbSet<MiljoeklasseType> MiljoeklasseType { get; set; }
        public DbSet<ModtagerAnlaeg> ModtagerAnlaeg { get; set; }
        public DbSet<OprindelsesstedKlassifikationType> OprindelsesstedKlassifikationType { get; set; }
        public DbSet<PlanlagteStikproever> PlanlagteStikproever { get; set; }
        public DbSet<Sagsbehandler> Sagsbehandler { get; set; }
        public DbSet<StatusBetaler> StatusBetaler { get; set; }
        public DbSet<StatusStikproeve> StatusStikproeve { get; set; }
        public DbSet<StatusStikproeveType> StatusStikproeveType { get; set; }
        public DbSet<Stikproeve> Stikproeve { get; set; }
        public DbSet<Transportoer> Transportoer { get; set; }
        public DbSet<Vognlaes> Vognlaes { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<StatusAnmeldelseType> StatusAnmeldelseType { get; set; }
        public DbSet<PersonJordmodtager> PersonJordmodtager { get; set; }
        public DbSet<PersonKommune> PersonKommune { get; set; }
        public DbSet<AnalyseDokument> AnalyseDokument { get; set; }
        public DbSet<BogholderOpslagstavle> BogholderOpslagstavle { get; set; }
        public DbSet<Jordforureningsopslag> Jordforureningsopslag { get; set; }
        public DbSet<KommuneJordklassifikation> KommuneJordklassifikation { get; set; }
        public DbSet<BemyndigedeAnmeldere> BemyndigedeAnmeldere { get; set; }
        public DbSet<Kommunikation> Kommunikation { get; set; }
        public DbSet<Advis> Advis { get; set; }
        public DbSet<Besked> Besked { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<Alarm> Alarm { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Delta> Delta { get; set; }
        public DbSet<AnalyseForureningskomponent> AnalyseForureningskomponent { get; set; }
        public DbSet<JordKlassifikationType> JordKlassifikationType { get; set; }
        public DbSet<LandsdelType> LandsdelType { get; set; }
        public DbSet<StatusAnmeldelse> StatusAnmeldelse { get; set; }
        public DbSet<NLogEntries> NLogEntries { get; set; }
        public DbSet<Anmeldelse> Anmeldelse { get; set; }
        public DbSet<Jord> Jord { get; set; }
        public DbSet<Oprindelsessted> Oprindelsessted { get; set; }
        public DbSet<AnmeldelseEffektivStatus> AnmeldelseEffektivStatus { get; set; }
        public DbSet<Opgavetype> Opgavetype { get; set; }
        public DbSet<GebyrTidsregistrering> GebyrTidsregistrering { get; set; }
        public DbSet<Gebyr> Gebyr { get; set; }
        public DbSet<FaktureringUdtraek> FaktureringUdtraek { get; set; }
    }
}
