//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JordKlassifikationType
    {
        public JordKlassifikationType()
        {
            this.Jordforureningsopslag = new HashSet<Jordforureningsopslag>();
            this.KommuneJordklassifikation = new HashSet<KommuneJordklassifikation>();
            this.ModtagerAnlaeg = new HashSet<ModtagerAnlaeg>();
            this.Jord = new HashSet<Jord>();
        }
    
        public System.Guid Id { get; set; }
        public string Navn { get; set; }
        public bool Aktiv { get; set; }
        public Nullable<decimal> Sortering { get; set; }
        public short Priotering { get; set; }
        public short Kode { get; set; }
        public System.Guid LandsdelTypeId { get; set; }
        public string Tooltip { get; set; }
    
        public virtual ICollection<Jordforureningsopslag> Jordforureningsopslag { get; set; }
        public virtual ICollection<KommuneJordklassifikation> KommuneJordklassifikation { get; set; }
        public virtual ICollection<ModtagerAnlaeg> ModtagerAnlaeg { get; set; }
        public virtual LandsdelType LandsdelType { get; set; }
        public virtual ICollection<Jord> Jord { get; set; }
    }
}
