//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jordmodtager
    {
        public Jordmodtager()
        {
            this.ModtagerAnlaeg = new HashSet<ModtagerAnlaeg>();
            this.StatusBetaler = new HashSet<StatusBetaler>();
            this.PersonJordmodtager = new HashSet<PersonJordmodtager>();
            this.BogholderOpslagstavle = new HashSet<BogholderOpslagstavle>();
        }
    
        public System.Guid Id { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Postnummer { get; set; }
        public string PostDistrikt { get; set; }
        public Nullable<decimal> Telefon { get; set; }
        public Nullable<decimal> CVR { get; set; }
        public Nullable<bool> AnvenderJF { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual ICollection<ModtagerAnlaeg> ModtagerAnlaeg { get; set; }
        public virtual ICollection<StatusBetaler> StatusBetaler { get; set; }
        public virtual ICollection<PersonJordmodtager> PersonJordmodtager { get; set; }
        public virtual ICollection<BogholderOpslagstavle> BogholderOpslagstavle { get; set; }
    }
}
