//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jord
    {
        public Jord()
        {
            this.Dokumentation = new HashSet<Dokumentation>();
            this.JordForureningskomponent = new HashSet<JordForureningskomponent>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JordKlassifikationTypeId { get; set; }
        public Nullable<System.Guid> AffaldTypeId { get; set; }
        public Nullable<System.Guid> JordflytningTypeId { get; set; }
        public string MiljoeTekniskTilsyn { get; set; }
        public Nullable<bool> Jordproever { get; set; }
        public Nullable<bool> JordproeverFoer { get; set; }
        public Nullable<decimal> ForventetJordmaengdeTon { get; set; }
        public Nullable<System.DateTime> KoerselStart { get; set; }
        public Nullable<System.DateTime> KoerselSlut { get; set; }
        public string AndenAffaldType { get; set; }
        public string Bemaerkning { get; set; }
        public string JordarbejdeBeskrivelse { get; set; }
        public string TidligereErhvervsaktivitet { get; set; }
        public bool IntaktJord { get; set; }
        public string AkutBaggrund { get; set; }
        public Nullable<bool> StraksGodkendJordhaandteringsplan { get; set; }
        public Nullable<decimal> AntalProever { get; set; }
        public string LinkTilGodkendtAnmeldelse { get; set; }
        public string EgetOrdrenummer { get; set; }
    
        public virtual AffaldType AffaldType { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
        public virtual ICollection<Dokumentation> Dokumentation { get; set; }
        public virtual ICollection<JordForureningskomponent> JordForureningskomponent { get; set; }
        public virtual JordKlassifikationType JordKlassifikationType { get; set; }
        public virtual JordflytningType JordflytningType { get; set; }
    }
}
