//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jordforureningsopslag
    {
        public System.Guid Id { get; set; }
        public System.Guid JordKlassifikationTypeId { get; set; }
        public bool V2 { get; set; }
        public bool V1 { get; set; }
        public bool OmkAnalysepligt { get; set; }
        public bool OmkLet { get; set; }
        public bool OmkRen { get; set; }
        public string KommunensMiljoeDb { get; set; }
        public System.DateTime Tid { get; set; }
    
        public virtual JordKlassifikationType JordKlassifikationType { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
