//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KommuneJordklassifikation
    {
        public System.Guid Id { get; set; }
        public System.Guid JordKlassifikationTypeId { get; set; }
        public System.Guid KommuneId { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual Kommune Kommune { get; set; }
        public virtual JordKlassifikationType JordKlassifikationType { get; set; }
    }
}
