//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kommune
    {
        public Kommune()
        {
            this.Konfig = new HashSet<Konfig>();
            this.PersonKommune = new HashSet<PersonKommune>();
            this.KommuneJordklassifikation = new HashSet<KommuneJordklassifikation>();
            this.Anmeldelse = new HashSet<Anmeldelse>();
            this.Opgavetype = new HashSet<Opgavetype>();
        }
    
        public System.Guid Id { get; set; }
        public string Navn { get; set; }
        public bool Aktiv { get; set; }
        public short Kommunenr { get; set; }
    
        public virtual ICollection<Konfig> Konfig { get; set; }
        public virtual ICollection<PersonKommune> PersonKommune { get; set; }
        public virtual ICollection<KommuneJordklassifikation> KommuneJordklassifikation { get; set; }
        public virtual ICollection<Anmeldelse> Anmeldelse { get; set; }
        public virtual ICollection<Opgavetype> Opgavetype { get; set; }
    }
}
