//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kommunikation
    {
        public System.Guid Id { get; set; }
        public System.Guid FraPerson { get; set; }
        public System.Guid TilPerson { get; set; }
        public System.Guid AnmeldelseId { get; set; }
        public System.Guid BeskedId { get; set; }
    
        public virtual Besked Besked { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
