//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konfig
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> KommuneId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual Kommune Kommune { get; set; }
    }
}
