//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandsdelType
    {
        public LandsdelType()
        {
            this.JordKlassifikationType = new HashSet<JordKlassifikationType>();
        }
    
        public System.Guid Id { get; set; }
        public int Kode { get; set; }
        public string Navn { get; set; }
        public int Sortering { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual ICollection<JordKlassifikationType> JordKlassifikationType { get; set; }
    }
}
