//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lastbil
    {
        public Lastbil()
        {
            this.Vognlaes = new HashSet<Vognlaes>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TransportoerId { get; set; }
        public System.Guid MiljoeklasseTypeId { get; set; }
        public string Fabrikat { get; set; }
        public string Nummerplade { get; set; }
        public string Bemærkning { get; set; }
        public bool Aktiv { get; set; }
        public decimal Nummer { get; set; }
        public System.DateTime Redigeret { get; set; }
    
        public virtual Transportoer Transportoer { get; set; }
        public virtual ICollection<Vognlaes> Vognlaes { get; set; }
        public virtual MiljoeklasseType MiljoeklasseType { get; set; }
    }
}
