//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public Log()
        {
            this.Delta = new HashSet<Delta>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StikproeveId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<System.Guid> AnmeldelseId { get; set; }
        public System.DateTime Dato { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Stikproeve Stikproeve { get; set; }
        public virtual ICollection<Delta> Delta { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
