//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrikel
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OprindelsesstedId { get; set; }
        public string Matrikelnr { get; set; }
        public string Ejerlav { get; set; }
        public string Sogn { get; set; }
        public string Herred { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public System.Data.Spatial.DbGeometry Geom { get; set; }
        public string Ejerlavsnavn { get; set; }
    
        public virtual Oprindelsessted Oprindelsessted { get; set; }
    }
}
