//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiljoeklasseType
    {
        public MiljoeklasseType()
        {
            this.Lastbil = new HashSet<Lastbil>();
        }
    
        public System.Guid Id { get; set; }
        public string Navn { get; set; }
        public Nullable<decimal> Sortering { get; set; }
        public bool Aktiv { get; set; }
        public short Kode { get; set; }
    
        public virtual ICollection<Lastbil> Lastbil { get; set; }
    }
}
