//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModtagerAnlaeg
    {
        public ModtagerAnlaeg()
        {
            this.Dokumenter = new HashSet<Dokumenter>();
            this.Graensevaerdier = new HashSet<Graensevaerdier>();
            this.Anmeldelse = new HashSet<Anmeldelse>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JordmodtagerId { get; set; }
        public Nullable<System.Guid> JordanlaegTypeId { get; set; }
        public Nullable<System.Guid> JordKlassifikationTypeId { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Postnummer { get; set; }
        public string PostDistrikt { get; set; }
        public string Ejerlav { get; set; }
        public string Matrikelnr { get; set; }
        public string www { get; set; }
        public string OffentligBemaerkning { get; set; }
        public Nullable<decimal> StikproeveFrekvens { get; set; }
        public System.Data.Spatial.DbGeometry Geom { get; set; }
        public bool AnvenderJF { get; set; }
        public bool Aktiv { get; set; }
        public Nullable<decimal> AntalBaase { get; set; }
        public Nullable<decimal> AdvisLabBaas { get; set; }
        public bool Affald { get; set; }
        public decimal Nummer { get; set; }
        public bool AutoGodkend { get; set; }
        public string KontaktpersonNavn { get; set; }
        public Nullable<decimal> KontaktpersonTlf { get; set; }
        public string KontaktpersonEmail { get; set; }
        public Nullable<int> KommuneKode { get; set; }
        public string Bemaerkning { get; set; }
        public Nullable<System.DateTime> AktivFra { get; set; }
        public Nullable<System.DateTime> AktivTil { get; set; }
        public bool Advis { get; set; }
        public bool OphaevAutoGodkendAnmKom { get; set; }
        public bool AnmelderOprettetMidlertidigtAnlaeg { get; set; }
        public bool CentraltOprettetMidlertidigtAnlaeg { get; set; }
        public string Ejerlavsnavn { get; set; }
        public string EsrEjendomsnr { get; set; }
    
        public virtual BetingelserJordtip BetingelserJordtip { get; set; }
        public virtual ICollection<Dokumenter> Dokumenter { get; set; }
        public virtual ICollection<Graensevaerdier> Graensevaerdier { get; set; }
        public virtual JordanlaegType JordanlaegType { get; set; }
        public virtual Jordmodtager Jordmodtager { get; set; }
        public virtual JordKlassifikationType JordKlassifikationType { get; set; }
        public virtual ICollection<Anmeldelse> Anmeldelse { get; set; }
    }
}
