//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opgavetype
    {
        public Opgavetype()
        {
            this.GebyrTidsregistrering = new HashSet<GebyrTidsregistrering>();
        }
    
        public System.Guid Id { get; set; }
        public int Kode { get; set; }
        public string Navn { get; set; }
        public decimal Timepris { get; set; }
        public Nullable<System.DateTime> FraDato { get; set; }
        public Nullable<System.DateTime> TilDato { get; set; }
        public int Sortering { get; set; }
        public int Afrunding { get; set; }
        public Nullable<int> KMDOpusMaterialeVareNummer { get; set; }
        public string KMDOpusPSPElementNummer { get; set; }
    
        public virtual Kommune Kommune { get; set; }
        public virtual ICollection<GebyrTidsregistrering> GebyrTidsregistrering { get; set; }
    }
}
