//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprindelsessted
    {
        public Oprindelsessted()
        {
            this.Matrikel = new HashSet<Matrikel>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OprindelsesstedKlassifikationTypeId { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Postnummer { get; set; }
        public string PostDistrikt { get; set; }
        public string TidligereErhvervsAktivitet { get; set; }
        public string Kortlagt { get; set; }
        public System.Data.Spatial.DbGeometry Geom { get; set; }
        public string OffvejUrl { get; set; }
        public string Beskrivelse { get; set; }
        public Nullable<System.Guid> AndenOprindJordTypeID { get; set; }
    
        public virtual AndenOprindJordType AndenOprindJordType { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
        public virtual ICollection<Matrikel> Matrikel { get; set; }
        public virtual OprindelsesstedKlassifikationType OprindelsesstedKlassifikationType { get; set; }
    }
}
