//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Advis = new HashSet<Advis>();
            this.BogholderOpslagstavle = new HashSet<BogholderOpslagstavle>();
            this.Kommunikation = new HashSet<Kommunikation>();
            this.Kommunikation1 = new HashSet<Kommunikation>();
            this.PersonJordmodtager = new HashSet<PersonJordmodtager>();
            this.PersonKommune = new HashSet<PersonKommune>();
            this.PlanlagteStikproever = new HashSet<PlanlagteStikproever>();
            this.StatusStikproeve = new HashSet<StatusStikproeve>();
            this.Stikproeve = new HashSet<Stikproeve>();
            this.Alarm = new HashSet<Alarm>();
            this.Log = new HashSet<Log>();
            this.StatusAnmeldelse = new HashSet<StatusAnmeldelse>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FirmaoplysningerId { get; set; }
        public string Navn { get; set; }
        public string Efternavn { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Postnummer { get; set; }
        public string Postdistrikt { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Telefon { get; set; }
        public Nullable<decimal> Mobiltelefon { get; set; }
        public bool Aktiv { get; set; }
        public Nullable<bool> GodkendtAfFirma { get; set; }
        public int BrugerId { get; set; }
        public string By { get; set; }
        public bool FrivilligeAdvis { get; set; }
        public Nullable<int> KoertJordAlarm { get; set; }
        public bool JordmodtagerAdvis { get; set; }
    
        public virtual ICollection<Advis> Advis { get; set; }
        public virtual Anmelder Anmelder { get; set; }
        public virtual Betaler Betaler { get; set; }
        public virtual ICollection<BogholderOpslagstavle> BogholderOpslagstavle { get; set; }
        public virtual Firmaoplysninger Firmaoplysninger { get; set; }
        public virtual ICollection<Kommunikation> Kommunikation { get; set; }
        public virtual ICollection<Kommunikation> Kommunikation1 { get; set; }
        public virtual ICollection<PersonJordmodtager> PersonJordmodtager { get; set; }
        public virtual ICollection<PersonKommune> PersonKommune { get; set; }
        public virtual ICollection<PlanlagteStikproever> PlanlagteStikproever { get; set; }
        public virtual Sagsbehandler Sagsbehandler { get; set; }
        public virtual ICollection<StatusStikproeve> StatusStikproeve { get; set; }
        public virtual ICollection<Stikproeve> Stikproeve { get; set; }
        public virtual Transportoer Transportoer { get; set; }
        public virtual ICollection<Alarm> Alarm { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<StatusAnmeldelse> StatusAnmeldelse { get; set; }
    }
}
