//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sagsbehandler
    {
        public Sagsbehandler()
        {
            this.Anmeldelse = new HashSet<Anmeldelse>();
            this.Gebyr = new HashSet<Gebyr>();
            this.Gebyr1 = new HashSet<Gebyr>();
            this.GebyrTidsregistrering = new HashSet<GebyrTidsregistrering>();
            this.FaktureringUdtraek = new HashSet<FaktureringUdtraek>();
            this.FaktureringUdtraek1 = new HashSet<FaktureringUdtraek>();
        }
    
        public System.Guid Id { get; set; }
        public string Filnavn { get; set; }
        public string Sti { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Anmeldelse> Anmeldelse { get; set; }
        public virtual ICollection<Gebyr> Gebyr { get; set; }
        public virtual ICollection<Gebyr> Gebyr1 { get; set; }
        public virtual ICollection<GebyrTidsregistrering> GebyrTidsregistrering { get; set; }
        public virtual ICollection<FaktureringUdtraek> FaktureringUdtraek { get; set; }
        public virtual ICollection<FaktureringUdtraek> FaktureringUdtraek1 { get; set; }
    }
}
