//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusAnmeldelse
    {
        public System.Guid Id { get; set; }
        public System.Guid AnmeldelseId { get; set; }
        public System.Guid StatusAnmeldelseTypeId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public System.DateTime Tid { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual StatusAnmeldelseType StatusAnmeldelseType { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
