//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusBetaler
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JordmodtagerId { get; set; }
        public Nullable<System.Guid> BetalerId { get; set; }
        public Nullable<bool> Godkendt { get; set; }
        public string Bemaerkning { get; set; }
        public Nullable<bool> KerneKunde { get; set; }
        public System.DateTime Redigeret { get; set; }
    
        public virtual Betaler Betaler { get; set; }
        public virtual Jordmodtager Jordmodtager { get; set; }
    }
}
