//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stikproeve
    {
        public Stikproeve()
        {
            this.PlanlagteStikproever = new HashSet<PlanlagteStikproever>();
            this.StatusStikproeve = new HashSet<StatusStikproeve>();
            this.AnalyseDokument = new HashSet<AnalyseDokument>();
            this.Log = new HashSet<Log>();
            this.AnalyseForureningskomponent = new HashSet<AnalyseForureningskomponent>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> VognlaesId { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public Nullable<decimal> Baas { get; set; }
        public Nullable<System.DateTime> JordFjernet { get; set; }
        public Nullable<System.Guid> LabPersonId { get; set; }
        public string AfvisBemaerkning { get; set; }
        public string InternBemaerkning { get; set; }
        public string Lugtvurdering { get; set; }
        public string JordproeveBeskrivelse { get; set; }
        public decimal Nummer { get; set; }
    
        public virtual ICollection<PlanlagteStikproever> PlanlagteStikproever { get; set; }
        public virtual ICollection<StatusStikproeve> StatusStikproeve { get; set; }
        public virtual Vognlaes Vognlaes { get; set; }
        public virtual ICollection<AnalyseDokument> AnalyseDokument { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<AnalyseForureningskomponent> AnalyseForureningskomponent { get; set; }
    }
}
