//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportoer
    {
        public Transportoer()
        {
            this.Lastbil = new HashSet<Lastbil>();
            this.Anmeldelse = new HashSet<Anmeldelse>();
        }
    
        public System.Guid Id { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual ICollection<Lastbil> Lastbil { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Anmeldelse> Anmeldelse { get; set; }
    }
}
