//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vognlaes
    {
        public Vognlaes()
        {
            this.Stikproeve = new HashSet<Stikproeve>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid LastbilId { get; set; }
        public Nullable<System.Guid> AnmeldelseId { get; set; }
        public System.DateTime Dato { get; set; }
        public Nullable<decimal> MaengdeTon { get; set; }
        public Nullable<decimal> MaengdeAksler { get; set; }
        public bool Afvist { get; set; }
        public string AfvistNote { get; set; }
    
        public virtual Lastbil Lastbil { get; set; }
        public virtual ICollection<Stikproeve> Stikproeve { get; set; }
        public virtual Anmeldelse Anmeldelse { get; set; }
    }
}
