<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title></title>
  $style()$
</head>
<body>
  <a name="top" id="top"></a>
  <table width="100%" cellspacing="0" cellpadding="0" bgcolor="#f5f6f4">
    <tr>
      <td align="center">
        <table width="600" cellspacing="0" cellpadding="0">
          <tr>
            <td align="center" class="permission"></td>
          </tr>
          <tr>
            <td height="77" align="left">
              <div id="topBar">
                <div style="float: right; margin-right: 10px; margin-top: 15px">FlytJord.dk</div>
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center">
        <table width="600" cellspacing="0" cellpadding="0" class="body">
          <tr>
            <td align="left" valign="top" width="348" class="mainbar">
              <p>
                Til $navn$
              </p>
              <p>$anmelder$ har oprettet en anmeldelse om jordflytning fra følgende adresse: $oprindelsesstedadresse$ til dette anmelderoprettede midlertidige anlæg $modtageanlaeg$.

							</p>
							<p>
								Hvis I kan godkende det midlertidige modtageanlæg, skal du trykke på dette link:<br/>
								<a href="$acceptlink$">$acceptlink$</a>
							</p>
							<p>
								Hvis I IKKE kan godkende det midlertidige modtageanlæg, skal du trykke på dette link:<br/>
								<a href="$afvislink$">$afvislink$</a>
							</p>
							<p>
								OBS: <br/>Anmeldelse af jordflytningen vil ikke kunne blive behandlet, før I har taget stilling til det midlertidige anlæg.
							</p>
							<p>OBS: Denne mail er fremsendt af FlytJord og kan ikke besvares. </p>
            </td>
            <td align="center" valign="top" width="219" class="sidebar">
              <h2>Link</h2>
              <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td class="sidebg" align="center">
                    <ul>
                      <li><a href="$linkanmeldelse$">Vis anmeldelsen</a></li>
                    </ul>
                  </td>
                </tr>
              </table>

            </td>
          </tr>
          <tr>
            <td colspan="2" align="center">&nbsp;
              <div id="Footer">
              <div style="float: left; margin-right: 10px; ">&nbsp;</div>  
              </div>
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
  </table>
</body>
</html>
