//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Niras.Jordflytning.Core.dk.niras.informatik.emailservice {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmailServiceSoap", Namespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/")]
    public partial class EmailService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailByNirasSMTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailWithBccByNirasSMTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailWithAttachmentsByNirasSMTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsEmailSentToAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback PutFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmailService() {
            this.Url = global::Niras.Jordflytning.Core.Properties.Settings.Default.Niras_Jordflytning_Core_dk_niras_informatik_emailservice_EmailService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event SendEmailByNirasSMTPCompletedEventHandler SendEmailByNirasSMTPCompleted;
        
        /// <remarks/>
        public event SendEmailWithBccByNirasSMTPCompletedEventHandler SendEmailWithBccByNirasSMTPCompleted;
        
        /// <remarks/>
        public event SendEmailWithAttachmentsByNirasSMTPCompletedEventHandler SendEmailWithAttachmentsByNirasSMTPCompleted;
        
        /// <remarks/>
        public event IsEmailSentToAllCompletedEventHandler IsEmailSentToAllCompleted;
        
        /// <remarks/>
        public event GetEmailObjectCompletedEventHandler GetEmailObjectCompleted;
        
        /// <remarks/>
        public event PutFileCompletedEventHandler PutFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/SendEmail", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendEmail(string senderId, System.DateTime senderTimestamp, string emailSubject, string emailContent, Recipient[] listRecipients, string customerName, string customerPassword, bool delayedsend, System.DateTime delayedSendTime) {
            this.Invoke("SendEmail", new object[] {
                        senderId,
                        senderTimestamp,
                        emailSubject,
                        emailContent,
                        listRecipients,
                        customerName,
                        customerPassword,
                        delayedsend,
                        delayedSendTime});
        }
        
        /// <remarks/>
        public void SendEmailAsync(string senderId, System.DateTime senderTimestamp, string emailSubject, string emailContent, Recipient[] listRecipients, string customerName, string customerPassword, bool delayedsend, System.DateTime delayedSendTime) {
            this.SendEmailAsync(senderId, senderTimestamp, emailSubject, emailContent, listRecipients, customerName, customerPassword, delayedsend, delayedSendTime, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string senderId, System.DateTime senderTimestamp, string emailSubject, string emailContent, Recipient[] listRecipients, string customerName, string customerPassword, bool delayedsend, System.DateTime delayedSendTime, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        senderId,
                        senderTimestamp,
                        emailSubject,
                        emailContent,
                        listRecipients,
                        customerName,
                        customerPassword,
                        delayedsend,
                        delayedSendTime}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/SendEmailByNirasSMTP", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendEmailByNirasSMTP(string emailFrom, string emailSubject, string emailContent, string emailTo) {
            this.Invoke("SendEmailByNirasSMTP", new object[] {
                        emailFrom,
                        emailSubject,
                        emailContent,
                        emailTo});
        }
        
        /// <remarks/>
        public void SendEmailByNirasSMTPAsync(string emailFrom, string emailSubject, string emailContent, string emailTo) {
            this.SendEmailByNirasSMTPAsync(emailFrom, emailSubject, emailContent, emailTo, null);
        }
        
        /// <remarks/>
        public void SendEmailByNirasSMTPAsync(string emailFrom, string emailSubject, string emailContent, string emailTo, object userState) {
            if ((this.SendEmailByNirasSMTPOperationCompleted == null)) {
                this.SendEmailByNirasSMTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailByNirasSMTPOperationCompleted);
            }
            this.InvokeAsync("SendEmailByNirasSMTP", new object[] {
                        emailFrom,
                        emailSubject,
                        emailContent,
                        emailTo}, this.SendEmailByNirasSMTPOperationCompleted, userState);
        }
        
        private void OnSendEmailByNirasSMTPOperationCompleted(object arg) {
            if ((this.SendEmailByNirasSMTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailByNirasSMTPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/SendEmailWithBccByNir" +
            "asSMTP", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendEmailWithBccByNirasSMTP(string emailFrom, string emailSubject, string emailContent, string emailTo, string emailBcc) {
            this.Invoke("SendEmailWithBccByNirasSMTP", new object[] {
                        emailFrom,
                        emailSubject,
                        emailContent,
                        emailTo,
                        emailBcc});
        }
        
        /// <remarks/>
        public void SendEmailWithBccByNirasSMTPAsync(string emailFrom, string emailSubject, string emailContent, string emailTo, string emailBcc) {
            this.SendEmailWithBccByNirasSMTPAsync(emailFrom, emailSubject, emailContent, emailTo, emailBcc, null);
        }
        
        /// <remarks/>
        public void SendEmailWithBccByNirasSMTPAsync(string emailFrom, string emailSubject, string emailContent, string emailTo, string emailBcc, object userState) {
            if ((this.SendEmailWithBccByNirasSMTPOperationCompleted == null)) {
                this.SendEmailWithBccByNirasSMTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailWithBccByNirasSMTPOperationCompleted);
            }
            this.InvokeAsync("SendEmailWithBccByNirasSMTP", new object[] {
                        emailFrom,
                        emailSubject,
                        emailContent,
                        emailTo,
                        emailBcc}, this.SendEmailWithBccByNirasSMTPOperationCompleted, userState);
        }
        
        private void OnSendEmailWithBccByNirasSMTPOperationCompleted(object arg) {
            if ((this.SendEmailWithBccByNirasSMTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailWithBccByNirasSMTPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/SendEmailWithAttachme" +
            "ntsByNirasSMTP", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendEmailWithAttachmentsByNirasSMTP(string emailFrom, string emailSubject, string emailContent, string emailTo, string emailBcc, string[] attachmentNames, byte[][] attachments) {
            this.Invoke("SendEmailWithAttachmentsByNirasSMTP", new object[] {
                        emailFrom,
                        emailSubject,
                        emailContent,
                        emailTo,
                        emailBcc,
                        attachmentNames,
                        attachments});
        }
        
        /// <remarks/>
        public void SendEmailWithAttachmentsByNirasSMTPAsync(string emailFrom, string emailSubject, string emailContent, string emailTo, string emailBcc, string[] attachmentNames, byte[][] attachments) {
            this.SendEmailWithAttachmentsByNirasSMTPAsync(emailFrom, emailSubject, emailContent, emailTo, emailBcc, attachmentNames, attachments, null);
        }
        
        /// <remarks/>
        public void SendEmailWithAttachmentsByNirasSMTPAsync(string emailFrom, string emailSubject, string emailContent, string emailTo, string emailBcc, string[] attachmentNames, byte[][] attachments, object userState) {
            if ((this.SendEmailWithAttachmentsByNirasSMTPOperationCompleted == null)) {
                this.SendEmailWithAttachmentsByNirasSMTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailWithAttachmentsByNirasSMTPOperationCompleted);
            }
            this.InvokeAsync("SendEmailWithAttachmentsByNirasSMTP", new object[] {
                        emailFrom,
                        emailSubject,
                        emailContent,
                        emailTo,
                        emailBcc,
                        attachmentNames,
                        attachments}, this.SendEmailWithAttachmentsByNirasSMTPOperationCompleted, userState);
        }
        
        private void OnSendEmailWithAttachmentsByNirasSMTPOperationCompleted(object arg) {
            if ((this.SendEmailWithAttachmentsByNirasSMTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailWithAttachmentsByNirasSMTPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/IsEmailSentToAll", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsEmailSentToAll(string senderId, System.DateTime sendersTimestamp, string customerName, string customerPassword) {
            object[] results = this.Invoke("IsEmailSentToAll", new object[] {
                        senderId,
                        sendersTimestamp,
                        customerName,
                        customerPassword});
            return ((System.Nullable<bool>)(results[0]));
        }
        
        /// <remarks/>
        public void IsEmailSentToAllAsync(string senderId, System.DateTime sendersTimestamp, string customerName, string customerPassword) {
            this.IsEmailSentToAllAsync(senderId, sendersTimestamp, customerName, customerPassword, null);
        }
        
        /// <remarks/>
        public void IsEmailSentToAllAsync(string senderId, System.DateTime sendersTimestamp, string customerName, string customerPassword, object userState) {
            if ((this.IsEmailSentToAllOperationCompleted == null)) {
                this.IsEmailSentToAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsEmailSentToAllOperationCompleted);
            }
            this.InvokeAsync("IsEmailSentToAll", new object[] {
                        senderId,
                        sendersTimestamp,
                        customerName,
                        customerPassword}, this.IsEmailSentToAllOperationCompleted, userState);
        }
        
        private void OnIsEmailSentToAllOperationCompleted(object arg) {
            if ((this.IsEmailSentToAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsEmailSentToAllCompleted(this, new IsEmailSentToAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/GetEmailObject", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailData GetEmailObject(string senderId, System.DateTime senderTimestamp, string customerName, string customerPassword) {
            object[] results = this.Invoke("GetEmailObject", new object[] {
                        senderId,
                        senderTimestamp,
                        customerName,
                        customerPassword});
            return ((EmailData)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailObjectAsync(string senderId, System.DateTime senderTimestamp, string customerName, string customerPassword) {
            this.GetEmailObjectAsync(senderId, senderTimestamp, customerName, customerPassword, null);
        }
        
        /// <remarks/>
        public void GetEmailObjectAsync(string senderId, System.DateTime senderTimestamp, string customerName, string customerPassword, object userState) {
            if ((this.GetEmailObjectOperationCompleted == null)) {
                this.GetEmailObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailObjectOperationCompleted);
            }
            this.InvokeAsync("GetEmailObject", new object[] {
                        senderId,
                        senderTimestamp,
                        customerName,
                        customerPassword}, this.GetEmailObjectOperationCompleted, userState);
        }
        
        private void OnGetEmailObjectOperationCompleted(object arg) {
            if ((this.GetEmailObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailObjectCompleted(this, new GetEmailObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://informatik.niras.dk/Services/EmailService/2009/09/30/PutFile", RequestNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", ResponseNamespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PutFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] buffer, string filename) {
            this.Invoke("PutFile", new object[] {
                        buffer,
                        filename});
        }
        
        /// <remarks/>
        public void PutFileAsync(byte[] buffer, string filename) {
            this.PutFileAsync(buffer, filename, null);
        }
        
        /// <remarks/>
        public void PutFileAsync(byte[] buffer, string filename, object userState) {
            if ((this.PutFileOperationCompleted == null)) {
                this.PutFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutFileOperationCompleted);
            }
            this.InvokeAsync("PutFile", new object[] {
                        buffer,
                        filename}, this.PutFileOperationCompleted, userState);
        }
        
        private void OnPutFileOperationCompleted(object arg) {
            if ((this.PutFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/")]
    public partial class Recipient {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://informatik.niras.dk/Services/EmailService/2009/09/30/")]
    public partial class EmailData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmailByNirasSMTPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmailWithBccByNirasSMTPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmailWithAttachmentsByNirasSMTPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IsEmailSentToAllCompletedEventHandler(object sender, IsEmailSentToAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsEmailSentToAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsEmailSentToAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<bool> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<bool>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetEmailObjectCompletedEventHandler(object sender, GetEmailObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PutFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591