<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title></title>
  $style()$
</head>
<body>
  <a name="top" id="top"></a>
  <table width="100%" cellspacing="0" cellpadding="0" bgcolor="#f5f6f4">
    <tr>
      <td align="center">
        <table width="600" cellspacing="0" cellpadding="0">
          <tr>
            <td align="center" class="permission"></td>
          </tr>
          <tr>
            <td height="77" align="left">
              <div id="topBar">
                <div style="float: right; margin-right: 10px; margin-top: 15px">FlytJord.dk</div>
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center">
        <table width="600" cellspacing="0" cellpadding="0" class="body">
          <tr>
            <td align="left" valign="top" width="348" class="mainbar">
				<p>Til $tilkommune$ Kommune</p>
				<p>Norddjurs Kommune har modtaget en anmeldelse af flytning af jord til en ejendom i Jeres kommune. Vi sender derfor jordanmeldelsen i høring hos Jer. 
Jorden ønskes flyttet fra adressen $fraadresse$ til $tiladresse$. Anmeldelsen kan ses via linket til højre.</p>
				<p>I bedes angive om I kan godkende, at jorden køres til ovenstående adresse eller om jorden skal afvises, via dette link</p> 
				<p>$godkendafvislink$</p> 
				<p>Endvidere har I mulighed for at indsætte en begrundelse.</p>
				<p>I skal være opmærksomme på at denne mail ikke kan besvares. Hvis I ønsker at sende supplerende dokumenter til os eller kontakte os på anden vis, kan vi kontaktes via <a href="mailto:natur.miljoe@norddjurs.dk" target="_blank">natur.miljoe@norddjurs</a> eller telefon 8753 5410.</p>
				<p>$supplerendeoplysninger$</p>
				<br />
				<br />
				<p>Med venlig hilsen</p>
				<p>Natur og Miljø<br />
				Norddjurs Kommune</p>
				<br />
				<p>OBS: Denne mail er fremsendt af FlytJord og kan ikke besvares. </p>
            </td>
            <td align="center" valign="top" width="219" class="sidebar">
              <h2>Link</h2>
              <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td class="sidebg" align="center">
                    <ul>
                          <li><a href="$flytjordUrl$">Se anmeldelsen</a></li>
                    </ul>
                  </td>
                </tr>
              </table>

            </td>
          </tr>
          <tr>
            <td colspan="2" align="center">&nbsp;
              <div id="Footer">
              <div style="float: left; margin-right: 10px; ">&nbsp;</div>  
              </div>
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
  </table>
</body>
</html>
