//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkter PunkterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.ResponseHeader ResponseHeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkter Punkter {
            get {
                return this.PunkterField;
            }
            set {
                if ((object.ReferenceEquals(this.PunkterField, value) != true)) {
                    this.PunkterField = value;
                    this.RaisePropertyChanged("Punkter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.ResponseHeader ResponseHeader {
            get {
                return this.ResponseHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseHeaderField, value) != true)) {
                    this.ResponseHeaderField = value;
                    this.RaisePropertyChanged("ResponseHeader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkter", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt04 Punkt04Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt08 Punkt08Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt09 Punkt09Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt10 Punkt10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt11 Punkt11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt12 Punkt12Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt04 Punkt04 {
            get {
                return this.Punkt04Field;
            }
            set {
                if ((object.ReferenceEquals(this.Punkt04Field, value) != true)) {
                    this.Punkt04Field = value;
                    this.RaisePropertyChanged("Punkt04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt08 Punkt08 {
            get {
                return this.Punkt08Field;
            }
            set {
                if ((object.ReferenceEquals(this.Punkt08Field, value) != true)) {
                    this.Punkt08Field = value;
                    this.RaisePropertyChanged("Punkt08");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt09 Punkt09 {
            get {
                return this.Punkt09Field;
            }
            set {
                if ((object.ReferenceEquals(this.Punkt09Field, value) != true)) {
                    this.Punkt09Field = value;
                    this.RaisePropertyChanged("Punkt09");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt10 Punkt10 {
            get {
                return this.Punkt10Field;
            }
            set {
                if ((object.ReferenceEquals(this.Punkt10Field, value) != true)) {
                    this.Punkt10Field = value;
                    this.RaisePropertyChanged("Punkt10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt11 Punkt11 {
            get {
                return this.Punkt11Field;
            }
            set {
                if ((object.ReferenceEquals(this.Punkt11Field, value) != true)) {
                    this.Punkt11Field = value;
                    this.RaisePropertyChanged("Punkt11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt12 Punkt12 {
            get {
                return this.Punkt12Field;
            }
            set {
                if ((object.ReferenceEquals(this.Punkt12Field, value) != true)) {
                    this.Punkt12Field = value;
                    this.RaisePropertyChanged("Punkt12");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class ResponseHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebugTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebugText {
            get {
                return this.DebugTextField;
            }
            set {
                if ((object.ReferenceEquals(this.DebugTextField, value) != true)) {
                    this.DebugTextField = value;
                    this.RaisePropertyChanged("DebugText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusText {
            get {
                return this.StatusTextField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusTextField, value) != true)) {
                    this.StatusTextField = value;
                    this.RaisePropertyChanged("StatusText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt04", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt04 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool P04Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P04AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P04BField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool P04 {
            get {
                return this.P04Field;
            }
            set {
                if ((this.P04Field.Equals(value) != true)) {
                    this.P04Field = value;
                    this.RaisePropertyChanged("P04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P04A {
            get {
                return this.P04AField;
            }
            set {
                if ((this.P04AField.Equals(value) != true)) {
                    this.P04AField = value;
                    this.RaisePropertyChanged("P04A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P04B {
            get {
                return this.P04BField;
            }
            set {
                if ((this.P04BField.Equals(value) != true)) {
                    this.P04BField = value;
                    this.RaisePropertyChanged("P04B");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt08", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt08 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool P08Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt08Struktur[] P08StrukturField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool P08 {
            get {
                return this.P08Field;
            }
            set {
                if ((this.P08Field.Equals(value) != true)) {
                    this.P08Field = value;
                    this.RaisePropertyChanged("P08");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt08Struktur[] P08Struktur {
            get {
                return this.P08StrukturField;
            }
            set {
                if ((object.ReferenceEquals(this.P08StrukturField, value) != true)) {
                    this.P08StrukturField = value;
                    this.RaisePropertyChanged("P08Struktur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt09", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt09 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool P09Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt09Struktur[] P09StrukturField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool P09 {
            get {
                return this.P09Field;
            }
            set {
                if ((this.P09Field.Equals(value) != true)) {
                    this.P09Field = value;
                    this.RaisePropertyChanged("P09");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt09Struktur[] P09Struktur {
            get {
                return this.P09StrukturField;
            }
            set {
                if ((object.ReferenceEquals(this.P09StrukturField, value) != true)) {
                    this.P09StrukturField = value;
                    this.RaisePropertyChanged("P09Struktur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt10", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt10 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool P10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt10Struktur[] P10StrukturField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool P10 {
            get {
                return this.P10Field;
            }
            set {
                if ((this.P10Field.Equals(value) != true)) {
                    this.P10Field = value;
                    this.RaisePropertyChanged("P10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt10Struktur[] P10Struktur {
            get {
                return this.P10StrukturField;
            }
            set {
                if ((object.ReferenceEquals(this.P10StrukturField, value) != true)) {
                    this.P10StrukturField = value;
                    this.RaisePropertyChanged("P10Struktur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt11", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt11 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool P11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt11Struktur[] P11StrukturField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool P11 {
            get {
                return this.P11Field;
            }
            set {
                if ((this.P11Field.Equals(value) != true)) {
                    this.P11Field = value;
                    this.RaisePropertyChanged("P11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt11Struktur[] P11Struktur {
            get {
                return this.P11StrukturField;
            }
            set {
                if ((object.ReferenceEquals(this.P11StrukturField, value) != true)) {
                    this.P11StrukturField = value;
                    this.RaisePropertyChanged("P11Struktur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt12", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt12 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool P12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt12Struktur[] P12StrukturField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool P12 {
            get {
                return this.P12Field;
            }
            set {
                if ((this.P12Field.Equals(value) != true)) {
                    this.P12Field = value;
                    this.RaisePropertyChanged("P12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Punkt12Struktur[] P12Struktur {
            get {
                return this.P12StrukturField;
            }
            set {
                if ((object.ReferenceEquals(this.P12StrukturField, value) != true)) {
                    this.P12StrukturField = value;
                    this.RaisePropertyChanged("P12Struktur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marker", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    public enum Marker : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nej = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ja = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt08Struktur", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt08Struktur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P08AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P08BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P08CField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P08A {
            get {
                return this.P08AField;
            }
            set {
                if ((this.P08AField.Equals(value) != true)) {
                    this.P08AField = value;
                    this.RaisePropertyChanged("P08A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P08B {
            get {
                return this.P08BField;
            }
            set {
                if ((object.ReferenceEquals(this.P08BField, value) != true)) {
                    this.P08BField = value;
                    this.RaisePropertyChanged("P08B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P08C {
            get {
                return this.P08CField;
            }
            set {
                if ((this.P08CField.Equals(value) != true)) {
                    this.P08CField = value;
                    this.RaisePropertyChanged("P08C");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt09Struktur", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt09Struktur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P09AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Ejer P09BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Anlæg P09CField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P09A {
            get {
                return this.P09AField;
            }
            set {
                if ((this.P09AField.Equals(value) != true)) {
                    this.P09AField = value;
                    this.RaisePropertyChanged("P09A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Ejer P09B {
            get {
                return this.P09BField;
            }
            set {
                if ((this.P09BField.Equals(value) != true)) {
                    this.P09BField = value;
                    this.RaisePropertyChanged("P09B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Anlæg P09C {
            get {
                return this.P09CField;
            }
            set {
                if ((this.P09CField.Equals(value) != true)) {
                    this.P09CField = value;
                    this.RaisePropertyChanged("P09C");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ejer", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    public enum Ejer : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offentlig = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Privat = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anlæg", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    public enum Anlæg : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enkeltindvindingsanlæg = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IkkeAlmentVandforsyningsanlæg = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt10Struktur", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt10Struktur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P10AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Tank P10CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Nedsivning P10DField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P10A {
            get {
                return this.P10AField;
            }
            set {
                if ((this.P10AField.Equals(value) != true)) {
                    this.P10AField = value;
                    this.RaisePropertyChanged("P10A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Tank P10C {
            get {
                return this.P10CField;
            }
            set {
                if ((this.P10CField.Equals(value) != true)) {
                    this.P10CField = value;
                    this.RaisePropertyChanged("P10C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Nedsivning P10D {
            get {
                return this.P10DField;
            }
            set {
                if ((this.P10DField.Equals(value) != true)) {
                    this.P10DField = value;
                    this.RaisePropertyChanged("P10D");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tank", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    public enum Tank : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeptiktankTrixtank = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Samletank = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nedsivning", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    public enum Nedsivning : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nedsivningsanlæg = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt11Struktur", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt11Struktur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P11AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P11BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P11CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Nuancering P11DField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P11A {
            get {
                return this.P11AField;
            }
            set {
                if ((this.P11AField.Equals(value) != true)) {
                    this.P11AField = value;
                    this.RaisePropertyChanged("P11A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P11B {
            get {
                return this.P11BField;
            }
            set {
                if ((object.ReferenceEquals(this.P11BField, value) != true)) {
                    this.P11BField = value;
                    this.RaisePropertyChanged("P11B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P11C {
            get {
                return this.P11CField;
            }
            set {
                if ((object.ReferenceEquals(this.P11CField, value) != true)) {
                    this.P11CField = value;
                    this.RaisePropertyChanged("P11C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Nuancering P11D {
            get {
                return this.P11DField;
            }
            set {
                if ((this.P11DField.Equals(value) != true)) {
                    this.P11DField = value;
                    this.RaisePropertyChanged("P11D");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIdField, value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nuancering", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    public enum Nuancering : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F0 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IkkeNuanceretEndnu = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt12Struktur", Namespace="http://schemas.datacontract.org/2004/07/WsNetForvaltning")]
    [System.SerializableAttribute()]
    public partial class Punkt12Struktur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P12AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P12BField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P12A {
            get {
                return this.P12AField;
            }
            set {
                if ((this.P12AField.Equals(value) != true)) {
                    this.P12AField = value;
                    this.RaisePropertyChanged("P12A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Marker P12B {
            get {
                return this.P12BField;
            }
            set {
                if ((this.P12BField.Equals(value) != true)) {
                    this.P12BField = value;
                    this.RaisePropertyChanged("P12B");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeoEnvironServiceReference.IService_GeoEnviron")]
    public interface IService_GeoEnviron {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/ConnectedTo", ReplyAction="http://tempuri.org/IService_GeoEnviron/ConnectedToResponse")]
        string ConnectedTo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/ConnectedTo", ReplyAction="http://tempuri.org/IService_GeoEnviron/ConnectedToResponse")]
        System.Threading.Tasks.Task<string> ConnectedToAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/ConnectedToUsingDataContract", ReplyAction="http://tempuri.org/IService_GeoEnviron/ConnectedToUsingDataContractResponse")]
        Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType ConnectedToUsingDataContract(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/ConnectedToUsingDataContract", ReplyAction="http://tempuri.org/IService_GeoEnviron/ConnectedToUsingDataContractResponse")]
        System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType> ConnectedToUsingDataContractAsync(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendom", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendomResponse")]
        Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response HentOplysningerForEjendom(int kommunenr, int ejendomsnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendom", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendomResponse")]
        System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response> HentOplysningerForEjendomAsync(int kommunenr, int ejendomsnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendomUsingDataContract" +
            "", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendomUsingDataContract" +
            "Response")]
        Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType HentOplysningerForEjendomUsingDataContract(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendomUsingDataContract" +
            "", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForEjendomUsingDataContract" +
            "Response")]
        System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType> HentOplysningerForEjendomUsingDataContractAsync(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikel", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikelResponse")]
        Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response HentOplysningerForMatrikel(string landsejerlavskode, string matrikelnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikel", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikelResponse")]
        System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response> HentOplysningerForMatrikelAsync(string landsejerlavskode, string matrikelnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikelUsingDataContrac" +
            "t", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikelUsingDataContrac" +
            "tResponse")]
        Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType HentOplysningerForMatrikelUsingDataContract(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikelUsingDataContrac" +
            "t", ReplyAction="http://tempuri.org/IService_GeoEnviron/HentOplysningerForMatrikelUsingDataContrac" +
            "tResponse")]
        System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType> HentOplysningerForMatrikelUsingDataContractAsync(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_GeoEnvironChannel : Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.IService_GeoEnviron, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_GeoEnvironClient : System.ServiceModel.ClientBase<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.IService_GeoEnviron>, Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.IService_GeoEnviron {
        
        public Service_GeoEnvironClient() {
        }
        
        public Service_GeoEnvironClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_GeoEnvironClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_GeoEnvironClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_GeoEnvironClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConnectedTo() {
            return base.Channel.ConnectedTo();
        }
        
        public System.Threading.Tasks.Task<string> ConnectedToAsync() {
            return base.Channel.ConnectedToAsync();
        }
        
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType ConnectedToUsingDataContract(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite) {
            return base.Channel.ConnectedToUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType> ConnectedToUsingDataContractAsync(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite) {
            return base.Channel.ConnectedToUsingDataContractAsync(composite);
        }
        
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response HentOplysningerForEjendom(int kommunenr, int ejendomsnr) {
            return base.Channel.HentOplysningerForEjendom(kommunenr, ejendomsnr);
        }
        
        public System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response> HentOplysningerForEjendomAsync(int kommunenr, int ejendomsnr) {
            return base.Channel.HentOplysningerForEjendomAsync(kommunenr, ejendomsnr);
        }
        
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType HentOplysningerForEjendomUsingDataContract(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite) {
            return base.Channel.HentOplysningerForEjendomUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType> HentOplysningerForEjendomUsingDataContractAsync(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite) {
            return base.Channel.HentOplysningerForEjendomUsingDataContractAsync(composite);
        }
        
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response HentOplysningerForMatrikel(string landsejerlavskode, string matrikelnr) {
            return base.Channel.HentOplysningerForMatrikel(landsejerlavskode, matrikelnr);
        }
        
        public System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.Response> HentOplysningerForMatrikelAsync(string landsejerlavskode, string matrikelnr) {
            return base.Channel.HentOplysningerForMatrikelAsync(landsejerlavskode, matrikelnr);
        }
        
        public Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType HentOplysningerForMatrikelUsingDataContract(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite) {
            return base.Channel.HentOplysningerForMatrikelUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType> HentOplysningerForMatrikelUsingDataContractAsync(Niras.Jordflytning.Infrastructure.GeoEnvironServiceReference.CompositeType composite) {
            return base.Channel.HentOplysningerForMatrikelUsingDataContractAsync(composite);
        }
    }
}
