<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title></title>
  $style()$
</head>
<body>
  <a name="top" id="top"></a>
  <table width="100%" cellspacing="0" cellpadding="0" bgcolor="#f5f6f4">
    <tr>
      <td align="center">
        <table width="600" cellspacing="0" cellpadding="0">
          <tr>
            <td align="center" class="permission"></td>
          </tr>
          <tr>
            <td height="77" align="left">
              <div id="topBar">
                <div style="float: right; margin-right: 10px; margin-top: 15px">FlytJord.dk</div>
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center">
        <table width="600" cellspacing="0" cellpadding="0" class="body">
          <tr>
            <td align="left" valign="top" width="600" class="mainbar">
              <p>Bås $baas$ er netop fyldt med jord hos $modtageranlaegnavn$.</p>
							<p>Vi skal anmode om, at der bliver udtaget jordprøver til stikprøvekontrol i morgen.</p>

            </td>
          </tr>
          <tr>
            <td colspan="2" align="center">&nbsp;
              <div id="Footer">
              <div style="float: left; margin-right: 10px; ">&nbsp;</div>  
              </div>
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
  </table>
</body>
</html>
